name: solar-system-workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
   unit-testing:
    strategy:
      matrix:
        nodejs_verion: [18, 20]
        operating_system: [ubuntu-latest, macos-latest]
        exclude:
          - nodejs_verion: 18
            operating_system: macos-latest
    runs-on: ${{ matrix.operating_system }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup nodejs ${{ matrix.nodejs_verion }}
        uses: actions/setup-node@v4
        with:
         node-version: ${{ matrix.nodejs_verion }}

      - name: install dependencies
        run: npm install

      - name: unit unit-testing
        run: npm test
      
      - name: list files
        run: ls -ltr
        
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Mocha-Test-Result-${{ matrix.operating_system}}-node${{ matrix.nodejs_verion}}
          path: test-results.xml

   code-coverage:
     runs-on: ubuntu-latest
     steps:
      - name: checkout repo
        uses: actions/checkout@v4
      
      - name: setup nodejs 18
        uses: actions/setup-node@v4
        with:
         node-version: 18

      - name: install dependencies
        run: npm install

      - name: run code coverage
        run: npm run coverage
        continue-on-error: true

      - name: Archive test result
        uses: actions/upload-artifact@v4
        with: 
          name: code-coverage-report
          path: coverage
          retention-days: 1